---
title: "My CV"
---


A word document version of my CV can be found [here](https://mdaramay.github.io/CV-Daramay_mar'16.docx)

**MENVEKEH DARAMAY**

36 N 3rd Street. Darby, PA, 19023 |
Cell: 267-984-3647 |
Email: mdaramay@gmail.com

**Education**

University of Pennsylvania |
B.A. Cognitive Science, May 2015 |
Biological Basis of Behavior

**Training**

Mental Health First Aid, March 2014|
Trained to detect first signs of behavioral health issues

HIPAA and CITI
Certified in 2013 to Present

Computerized Neuropsychiatry Batteries |
Test for subjects’ working memory, emotional recognition, visual/spatial capabilities, etc.

Transcranial Direct Current Stimulation (tDCS)

Strategies for Trauma Awareness and Resilience |
Trained to understand and help break cycles of trauma

**Research Positions** 

Assistant. Hospital of the University of Pennsylvania (HUP), Dec 2012 – June 2014 |
Neuropsychiatry Division

Gained insight into schizophrenia and the effect on those who are afflicted by the disorder. I held three key roles: I organized and filed research folders and entered subject data into computer for later analysis. Additionally, I was trained as an experimenter who could run a few different types of studies. My first training was in Computerize Neuropsychiatry Batteries (CNB). CNB had series of cognitive test that tested subjects’ working memory, decision-making process, facial and emotional recognition, visual/spatial capabilities, reflex and more. Lastly, I was trained to run EEG studies in combination of eye trackers for studying the role of visual fixation in facial-emotional recognition in schizophrenic patients. 

Assistant. University of Pennsylvania School of Medicine, June 2014 – May 2015 |
Department of Neurology |

Over the summer my position was recruiting and scheduling coordinator for tDCS and TMS studies. I also maintained lab database for subject demographics. The following fall, I received training in tDCS and became certified to run subjects on my own. Thus, in addition to recruiting and scheduling interested subjects for at least three different studies, I administered tDCS for one of the studies. My particular study involved the effects of tDCS on working memory. 



**Experience**

International Development Summer Institute (IDSI), May-June 2012 

Through a partnership with Kwame Nkrumah University, I learned first hand by visiting hospitals and shadowing doctors the differences and unique challenges patients in Ghana face both in urban and rural settings.
Penn Reading Initiative, September 2011 – May 2012

Tutored elementary school children who were behind their grade level in reading. 

Focus First, Fall 2014

Volunteered with Focus First, which is a student group dedicated to serving low income communities through identifying children that might have vision problems and putting their family in contact with healthcare providers at little to no cost to the family.

Shadowing, Spring 2015

Shadowed my PI, Dr. Roy Hamilton on clinical visits to Penn Institute for Rehabilitation Medicine (PIRM) where he examined cases of patients with neurological deficits. 

ER Scribe, January – March 2016 |
PhysAssist Scribe, Inc. 

**Extracurricular**

University of Pennsylvania Muslim Student Association |
President, Social Co-chair, Education Co-chair 

University of Pennsylvania Men’s Club Soccer |
Team Member

**Distinctions**

Sphinx Senior Society

Selection to the most prestigious University of Pennsylvania honor society was based on leadership on campus.

Scholarship Recipient

Intl. Conference on Conflict Resolution Education

Spotlight Award |
For contributions made to the Muslim community at the University of Pennsylvania

